### ISSUE TITLE
Huge security concerns

### ISSUE THREAD

**Issue by ranjancse26** [rsksmart/rif-marketplace-nfts#24]
The contract - RNSSimplePlacementsV1 is not checking for the owner or sender or is not doing any such verification against the person calling the contract to transfer the domain.

**Comment by julianmrodri** [comment]
All operations (`place`, `unplace`) check the sender is the owner of the token. Unless you are buying in which that case you dont need to validate the sender, just need to ensure it is approved for transfer by the owner and that he is paying the correct price.

Can you point to the section of the code where you believe we should be adding a validation?

**Comment by julianmrodri** [comment]
If you refer to the`_transfer` function, it is `internal`. Can only be called from other functions  in the contract which are the ones doing the validation.
https://github.com/rsksmart/rif-marketplace-nfts/blob/8be8c5ad0f5c49c9f619dd47d31c5864fc03d986/contracts/RNSSimplePlacementsV1.sol#L27

**Comment by julianmrodri** [comment]
Closing as no response was received from user. Verified the contract and the situation mentioned is not occurring.
